=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.hr-xml.org/2007-04-15" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: AcknowledgeTypes.xsd
Status: Recommendation
Date this version: 2007-04-15
Purpose: Defines the Acknowledge schema
Author(s):  Paul Kiel, Dan Diman, Kim Bartkus
Documentation: ApplicationAcknowledgement.doc

Terms of license can be found in license.txt.

2005-10-26: Changed MessageIdType from an enumerated list to a simple string.  Made UniquePayloadTrackingId repeatable.  Review by the Technical Steering Committee recommended this.  Backwardly compatible.

2005-11-08: Changed EntityNoException from fixed=true to a single enumeration.  It is believed that this would be better supported by code generators.  No content model changes.

</xsd:documentation>
	</xsd:annotation>
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="../../W3C/xml.xsd"/>
	<xsd:include schemaLocation="./CPO/EntityIdType.xsd"/>
	<xsd:include schemaLocation="./CPO/PersonName.xsd"/>
	<xsd:include schemaLocation="./CPO/ContactMethod.xsd"/>
	<xsd:include schemaLocation="./CPO/UserArea.xsd"/>
	<xsd:complexType name="ExceptionType">
		<xsd:sequence>
			<xsd:element name="ExceptionIdentifier" type="xsd:string" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>This is an ID (or code) used by the organization generating the acknowledgement to identify the specific exception.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ExceptionSeverity">
				<xsd:annotation>
					<xsd:documentation>How severe the exception is.  Fatal means system processed nothing.  Warning means system processed something, but perhaps incompletely.  Information means system processed everything, but a problem *may* occur that needs notification.</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Fatal">
							<xsd:annotation>
								<xsd:documentation>Fatal means system processed nothing.  </xsd:documentation>
							</xsd:annotation>
						</xsd:enumeration>
						<xsd:enumeration value="Warning">
							<xsd:annotation>
								<xsd:documentation> Warning means system processed something, but perhaps incompletely.  </xsd:documentation>
							</xsd:annotation>
						</xsd:enumeration>
						<xsd:enumeration value="Information">
							<xsd:annotation>
								<xsd:documentation>Information means system processed everything, but a problem *may* occur that needs notification.</xsd:documentation>
							</xsd:annotation>
						</xsd:enumeration>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ExceptionMessage" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>The exception content message.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ExceptionScopeSchemaXPath" type="xsd:string" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The leve at which processing stops (within the entity).   If fatal severity, this will  match the EntitySchemaXPath.  If a warning severity, then this will be the point at which processing stops within entity.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SubordinateEntityXPath" type="xsd:string" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The offending element(s) or attributes (inside the scope of ExceptionScopeSchemaXPath, which in turn is in the scope of the EntityDisposition.  </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Followup" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Indicates who is responsibile for correcting the exception.</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="OrganizationId" type="EntityIdType" minOccurs="0"/>
						<xsd:element name="OrganizationName" type="xsd:string" minOccurs="0"/>
						<xsd:element name="PersonName" type="PersonNameType" minOccurs="0"/>
						<xsd:element name="ContactInfo" type="ContactMethodType" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
					<xsd:attribute name="responsibleForFollowup">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="No Followup Needed"/>
								<xsd:enumeration value="Payload Source Organization"/>
								<xsd:enumeration value="Acknowledgement Source Organization"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AdditionalData" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Additional information (in a name-value pair format).</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Description" type="xsd:string"/>
						<xsd:element name="Value" type="xsd:string"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="EntityExceptionType">
		<xsd:sequence>
			<xsd:element name="EntityXMLFragment" type="xsd:anyType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>XML fragment beginning with the element pointed to by the EntityInstanceXPath above.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Exception" type="ExceptionType" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Business level exceptions regarding the specified entity.  This would not include enveloping or xml related exceptions.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AcknowledgeType">
		<xsd:sequence>
			<xsd:element name="PayloadResponseSummary" type="PayloadResponseSummaryType"/>
			<xsd:element name="PayloadDisposition" type="PayloadDispositionType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation> Should the detail be optional?  Or should this be a choice between the element as it is now and a "no-op" element that indicates total success of the transaction.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element ref="UserArea" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute ref="xml:lang"/>
	</xsd:complexType>
	<xsd:complexType name="PayloadDispositionType">
		<xsd:sequence>
			<xsd:element name="EntityDisposition" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Dispostion for a single entity.  Repetable for batched entities.  For example, representing a Subscriber in Enrollment.</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="EntityIdentifier" type="EntityIdType" minOccurs="0">
							<xsd:annotation>
								<xsd:documentation>The identifier for the component disposition, for example SubscriberId</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:element name="EntityShortName" type="xsd:string" minOccurs="0">
							<xsd:annotation>
								<xsd:documentation>The Entity disposition name,.  Example is "Subscriber".</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:element name="EntitySchemaXPath" type="xsd:string" minOccurs="0">
							<xsd:annotation>
								<xsd:documentation>This will define the "root" level at which the exception applies by reference to the schema.  This is an XPath not for the XML payload instance, but the XML document that is the schema itself.</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:element name="EntityInstanceXPath" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation>XPath to the entity in the payload.  This is the full XPath and not simply pointing to the axis in general.  For example in Enrollment, this value would  be an XPath to the Subscriber element (including the occurrence of the Subscriber in the instance - such as Enrollment/Organization/Subscriber[position()=2]).</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:choice>
							<xsd:element name="EntityNoException">
								<xsd:annotation>
									<xsd:documentation>Entities successfully accepted in the payload transaction.</xsd:documentation>
								</xsd:annotation>
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="true"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="EntityException" type="EntityExceptionType">
								<xsd:annotation>
									<xsd:documentation>This is the main resuable that can be incorporated into SOAP fault scenario.!!!!</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:choice>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PayloadResponseSummaryType">
		<xsd:sequence>
			<xsd:element name="ReferenceId" type="EntityIdType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>An identifer passed back for referencing the transation. For example, an order number or confirmation code.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="TransportMessageId" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The message identifier of the enrollment transaction for which application acknowledgement is being returned.  Matches the transport layer id.</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="MessageIdType" type="xsd:string" minOccurs="0"/>
						<xsd:element name="MessageId" type="EntityIdType"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="UniquePayloadTrackingId" type="EntityIdType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The sender in a trading partnership agreeing to use the enrollment acknowledgement will provide this value in the attribute of the same name on the "Enrollment" element; the value will be repeated in this elemnt to produce an acknowledgement of a specific enrollment payload.  Matches the Enrollment Id.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="TransactionReceiptTimestamp" type="DateTimeType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The date and time at which the message containing the payload here acknowledged was received.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ProcessingTimestamp" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The date and time at which a particular processing action was performed on the payload.  The description attribute will contain text meaningful to both parties in the exchange.  For example, an acknolwegment sender could provide date/times such as "Medical Coverages Processed" or "Claims Ready".  Value applies to non-exception cases.</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="DateTimeType">
							<xsd:attribute name="description" type="xsd:string"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AcknowledgementCreationTimestamp" type="DateTimeType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The date and time at which this acknowledgement was created.  It is recommended to use the time at which the acknowledgement payload was completed.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ReceivedPayloadSummary" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="ReceivedPayloadSchemaURI" type="xsd:anyURI" minOccurs="0">
							<xsd:annotation>
								<xsd:documentation>A URI indicating where the schema used to create the enrolment payload being acknowledged can be found.</xsd:documentation>
							</xsd:annotation>
						</xsd:element>
						<xsd:element name="EntityInfo" minOccurs="0" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="EntityInstanceAxisXPath" type="xsd:string" minOccurs="0">
										<xsd:annotation>
											<xsd:documentation>An XPath to the entity level in the xml instance.  It does not indicate which occurrence of the entity, only the axis.  For example, it may be Enrollment/Organization/Subscriber - not indicating which Subscriber occurrence. The instance is located by ReceivedPayloadSchemaURI.</xsd:documentation>
										</xsd:annotation>
									</xsd:element>
									<xsd:element name="Count" type="xsd:nonNegativeInteger">
										<xsd:annotation>
											<xsd:documentation>The number of items referreed to in the EntitySchemaXPath element.</xsd:documentation>
										</xsd:annotation>
									</xsd:element>
									<xsd:element name="EntityShortName" type="xsd:string" minOccurs="0">
										<xsd:annotation>
											<xsd:documentation>A non-standard or shorter name for the entities identified by the EntityXPath  (e.g. "Families with Medical Coverage" or "Life Insurance Coverages with Total Volume Over 2 million dollars".</xsd:documentation>
										</xsd:annotation>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ApplicationAcknowledgement" type="AcknowledgeType"/>
</xsd:schema>

=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement3.xml
<?xml version="1.0" encoding="UTF-8"?><ApplicationAcknowledgement xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 ApplicationAcknowledgement.xsd">	<PayloadResponseSummary>		<TransportMessageId>			<MessageIdType>MQSeriesTransactionID</MessageIdType>			<MessageId>				<IdValue>444415555</IdValue>			</MessageId>		</TransportMessageId>		<UniquePayloadTrackingId>			<IdValue>0083333333330080000D59772004-05-17-18.40.33.000000137489755</IdValue>		</UniquePayloadTrackingId>		<TransactionReceiptTimestamp>2004-05-17T18:40:59Z</TransactionReceiptTimestamp>		<ProcessingTimestamp>2004-05-17T18:41:30Z</ProcessingTimestamp>		<AcknowledgementCreationTimestamp>2004-05-17T18:41:45Z</AcknowledgementCreationTimestamp>		<ReceivedPayloadSummary>			<ReceivedPayloadSchemaURI> http://ns.hr-xml_2-3/Enrollment.xsd </ReceivedPayloadSchemaURI>			<EntityInfo>				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber</EntityInstanceAxisXPath>				<Count>1</Count>				<EntityShortName>Subscribers</EntityShortName>			</EntityInfo>			<EntityInfo>				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber/Dependent</EntityInstanceAxisXPath>				<Count>2</Count>				<EntityShortName>Dependents</EntityShortName>			</EntityInfo>			<EntityInfo>				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber/Dependent[position()=1]</EntityInstanceAxisXPath>				<Count>1</Count>				<EntityShortName>Dependents with Errors</EntityShortName>			</EntityInfo>		</ReceivedPayloadSummary>	</PayloadResponseSummary>	<PayloadDisposition>		<EntityDisposition>			<EntityIdentifier>				<IdValue name="SocialSecurityNumber"> 536403123 </IdValue>			</EntityIdentifier>			<EntitySchemaXPath>/Enrollment/Organization/Subscriber</EntitySchemaXPath>			<EntityInstanceXPath>/Enrollment/Organization/Subscriber[position()=1]</EntityInstanceXPath>			<EntityException>				<Exception>					<ExceptionIdentifier>996</ExceptionIdentifier>					<ExceptionSeverity>Warning</ExceptionSeverity>					<ExceptionMessage>Missing Spouse SSN</ExceptionMessage>					<ExceptionScopeSchemaXPath>/Enrollment/Organization/Subscriber/Dependent[position()=1]</ExceptionScopeSchemaXPath>					<SubordinateEntityXPath>/Enrollment/Organization/Subscriber/Dependent[position()=1]/Person/IdentificationCode/IdValue</SubordinateEntityXPath>					<Followup responsibleForFollowup="Payload Source Organization">						<OrganizationId>							<IdValue name="TaxpayerID">444415555</IdValue>						</OrganizationId>						<OrganizationName>BeneFriends</OrganizationName>					</Followup>				</Exception>			</EntityException>		</EntityDisposition>	</PayloadDisposition></ApplicationAcknowledgement>

=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement5.xml
<?xml version="1.0" encoding="UTF-8"?><ApplicationAcknowledgement xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 ApplicationAcknowledgement.xsd">	<PayloadResponseSummary>		<TransportMessageId>			<MessageIdType>Defined by Trading Partners</MessageIdType>			<MessageId validFrom="notKnown" validTo="notKnown" idOwner="ACME">				<IdValue name="String">4561235484</IdValue>			</MessageId>		</TransportMessageId>		<UniquePayloadTrackingId>			<IdValue>174816425</IdValue>		</UniquePayloadTrackingId>		<TransactionReceiptTimestamp>2004-05-10T13:52:07Z</TransactionReceiptTimestamp>		<ProcessingTimestamp description="String">2004-05-10T14:00:00Z</ProcessingTimestamp>		<AcknowledgementCreationTimestamp>2004-05-11T02:01:32Z</AcknowledgementCreationTimestamp>		<ReceivedPayloadSummary>			<ReceivedPayloadSchemaURI>http://ns.hr-xml.org/2007-04-15/2_3/Enrollment/Enrollment.xsd</ReceivedPayloadSchemaURI>			<EntityInfo>				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber</EntityInstanceAxisXPath>				<Count>561</Count>				<EntityShortName>Subscriber</EntityShortName>			</EntityInfo>		</ReceivedPayloadSummary>	</PayloadResponseSummary>	<PayloadDisposition>		<EntityDisposition>			<EntityShortName>Enrollment</EntityShortName>			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>			<EntityInstanceXPath>/Enrollment[1]</EntityInstanceXPath>			<EntityException>				<Exception>					<ExceptionSeverity>Fatal</ExceptionSeverity>					<ExceptionMessage>Unknown Group</ExceptionMessage>					<ExceptionScopeSchemaXPath>Enrollment</ExceptionScopeSchemaXPath>					<Followup responsibleForFollowup="Payload Source Organization"/>				</Exception>			</EntityException>		</EntityDisposition>	</PayloadDisposition>	<UserArea/></ApplicationAcknowledgement>

=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement4.xml
<?xml version="1.0" encoding="UTF-8"?><ApplicationAcknowledgement xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 ApplicationAcknowledgement.xsd">	<PayloadResponseSummary>		<TransportMessageId>			<MessageIdType>MQSeriesTransactionID</MessageIdType>			<MessageId>				<IdValue>444415555</IdValue>			</MessageId>		</TransportMessageId>		<UniquePayloadTrackingId>			<IdValue>0083333333330080000D59772004-05-17-22.15.10.000000565887777</IdValue>		</UniquePayloadTrackingId>		<TransactionReceiptTimestamp>2004-05-17T22:20:00Z</TransactionReceiptTimestamp>		<ProcessingTimestamp>2004-05-17T22:40:30Z</ProcessingTimestamp>		<AcknowledgementCreationTimestamp>2004-05-17T22:41:05Z</AcknowledgementCreationTimestamp>		<ReceivedPayloadSummary>			<ReceivedPayloadSchemaURI> http://ns.hr-xml_2-3/Enrollment.xsd </ReceivedPayloadSchemaURI>			<EntityInfo>				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber</EntityInstanceAxisXPath>				<Count>1</Count>				<EntityShortName>Subscribers</EntityShortName>			</EntityInfo>		</ReceivedPayloadSummary>	</PayloadResponseSummary>	<PayloadDisposition>		<EntityDisposition>			<EntityIdentifier>				<IdValue name="SocialSecurityNumber">555632144</IdValue>			</EntityIdentifier>			<EntitySchemaXPath>/Enrollment/Organization/Subscriber</EntitySchemaXPath>			<EntityInstanceXPath>/Enrollment/Organization/Subscriber[position()=1]</EntityInstanceXPath>			<EntityException>				<Exception>					<ExceptionIdentifier>120</ExceptionIdentifier>					<ExceptionSeverity>Fatal</ExceptionSeverity>					<ExceptionMessage>Invalid Group Number</ExceptionMessage>					<ExceptionScopeSchemaXPath>/Enrollment/Organization/Subscriber</ExceptionScopeSchemaXPath>					<SubordinateEntityXPath>/Enrollment/Organization/Subscriber/Coverage/TierCoverage/GroupNumber</SubordinateEntityXPath>					<Followup responsibleForFollowup="Payload Source Organization">						<OrganizationId>							<IdValue name="Mutually Defined">444415555</IdValue>						</OrganizationId>						<OrganizationName>BeneFriends</OrganizationName>					</Followup>				</Exception>			</EntityException>		</EntityDisposition>	</PayloadDisposition></ApplicationAcknowledgement>

=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ApplicationAcknowledgement xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 ApplicationAcknowledgement.xsd">
	<PayloadResponseSummary>
		<TransportMessageId>
			<MessageIdType>MQSeriesTransactionID</MessageIdType>
			<MessageId validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premiere Company ">
				<IdValue name="identificationCodeValue">577012007</IdValue>
			</MessageId>
		</TransportMessageId>
		<UniquePayloadTrackingId>
			<IdValue>2004-04-02T01:23:01-34:00TPA Inc.</IdValue>
		</UniquePayloadTrackingId>
		<TransactionReceiptTimestamp>2004-04-02T01:00:00-09:00</TransactionReceiptTimestamp>
		<ProcessingTimestamp description="Medical Coverages Processed">2004-04-02T01:00:00-09:10</ProcessingTimestamp>
		<AcknowledgementCreationTimestamp>2004-04-02T01:00:00-09:20</AcknowledgementCreationTimestamp>
		<ReceivedPayloadSummary>
			<ReceivedPayloadSchemaURI>http://ns.hr-xml.org/2007-04-15/2_3/Enrollment/Enrollment.xsd</ReceivedPayloadSchemaURI>
			<EntityInfo>
				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber</EntityInstanceAxisXPath>
				<Count>2</Count>
				<EntityShortName>Subscriber without errors</EntityShortName>
			</EntityInfo>
			<EntityInfo>
				<EntityInstanceAxisXPath>/Enrollment</EntityInstanceAxisXPath>
				<Count>2</Count>
				<EntityShortName>Subscriber with errors</EntityShortName>
			</EntityInfo>
		</ReceivedPayloadSummary>
	</PayloadResponseSummary>
	<PayloadDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">32866</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment/Organization[1]/Subscriber[1]</EntityInstanceXPath>
			<EntityNoException>true</EntityNoException>
		</EntityDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">498576309</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment/Organization[1]/Subscriber[2]</EntityInstanceXPath>
			<EntityException>
				<Exception>
					<ExceptionIdentifier>5508</ExceptionIdentifier>
					<ExceptionSeverity>Warning</ExceptionSeverity>
					<ExceptionMessage> Subscriber's given name truncate value to 12 characters</ExceptionMessage>
					<ExceptionScopeSchemaXPath>/Enrollment/Organization[1]/Subscriber[2]/Person//PersonName/FamilyName</ExceptionScopeSchemaXPath>
					<Followup responsibleForFollowup="No Followup Needed"/>
				</Exception>
			</EntityException>
		</EntityDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">09847</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment/Organization[1]/Subscriber[3]</EntityInstanceXPath>
			<EntityNoException>true</EntityNoException>
		</EntityDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">98434</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment /Organization[1]/Subscriber[4]</EntityInstanceXPath>
			<EntityException>
				<Exception>
					<ExceptionIdentifier>5599</ExceptionIdentifier>
					<ExceptionSeverity>Fatal</ExceptionSeverity>
					<ExceptionMessage>Subscriber's given name is missing or blank.</ExceptionMessage>
					<ExceptionScopeSchemaXPath>/Enrollment/Organization[1]/Subscriber[4]/Person//PersonName/GivenNam</ExceptionScopeSchemaXPath>
					<Followup responsibleForFollowup="Payload Source Organization">
						<OrganizationId>
							<IdValue name="identificationCodeValue">99384884</IdValue>
						</OrganizationId>
						<OrganizationName>TPA Inc. </OrganizationName>
					</Followup>
				</Exception>
			</EntityException>
		</EntityDisposition>
	</PayloadDisposition>
</ApplicationAcknowledgement>

=== raml-apis/Jobvite/schemas/CPO/ApplicationAcknowledgement1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ApplicationAcknowledgement xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 ApplicationAcknowledgement.xsd">
	<PayloadResponseSummary>
		<TransportMessageId>
			<MessageIdType>MQSeriesTransactionID</MessageIdType>
			<MessageId validFrom="2004-04-01T01:00:00-00:00" validTo="2004-04-02T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="identificationCodeValue">577012007</IdValue>
			</MessageId>
		</TransportMessageId>
		<UniquePayloadTrackingId>
			<IdValue>2004-04-01T01:01:00-00:00TPA Inc</IdValue>
		</UniquePayloadTrackingId>
		<TransactionReceiptTimestamp>2004-04-01T01:00:00-09:00</TransactionReceiptTimestamp>
		<ProcessingTimestamp description="Medical Coverages Processed">2004-04-01T01:00:00-09:10</ProcessingTimestamp>
		<AcknowledgementCreationTimestamp>2004-04-01T01:00:00-09:20</AcknowledgementCreationTimestamp>
		<ReceivedPayloadSummary>
			<ReceivedPayloadSchemaURI>http://ns.hr-xml.org/2007-04-15/2_3/Enrollment/Enrollment.xsd</ReceivedPayloadSchemaURI>
			<EntityInfo>
				<EntityInstanceAxisXPath>/Enrollment/Organization/Subscriber</EntityInstanceAxisXPath>
				<Count>2</Count>
				<EntityShortName>Subscriber</EntityShortName>
			</EntityInfo>
		</ReceivedPayloadSummary>
	</PayloadResponseSummary>
	<PayloadDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-01T01:00:00-00:00" validTo="2004-04-02T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">32866</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment/Organization[1]/Subscriber[1]</EntityInstanceXPath>
			<EntityNoException>true</EntityNoException>
		</EntityDisposition>
		<EntityDisposition>
			<EntityIdentifier validFrom="2004-04-02T01:00:00-00:00" validTo="2004-04-03T01:00:00-00:00" idOwner="Premier Company">
				<IdValue name="employeeId">32867</IdValue>
			</EntityIdentifier>
			<EntityShortName>Medical Enrollment</EntityShortName>
			<EntitySchemaXPath>/Enrollment</EntitySchemaXPath>
			<EntityInstanceXPath>/Enrollment/Organization[1]/Subscriber[2]</EntityInstanceXPath>
			<EntityNoException>true</EntityNoException>
		</EntityDisposition>
	</PayloadDisposition>
</ApplicationAcknowledgement>
