=== raml-apis/Jobvite/schemas/CPO/JobHeader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ns.hr-xml.org/2007-04-15" xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: JobHeader.xsd
Status: Recommendation
Date this version: 2007-04-15
Purpose: Defines the Schema for Job Description
Author(s): Brian Salamon, Kim Bartkus, Paul Kiel, J/P Workgroup
Documentation: JobAndPositionHeader.html

Terms of license can be found in license.txt.

</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="./CPO/DateTimeDataTypes.xsd"/>
	<xsd:element name="JobHeader">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="JobId" type="JobIdentifierType"/>
				<xsd:element ref="JobTitle" minOccurs="0"/>
				<xsd:element ref="JobDescription" minOccurs="0"/>
				<xsd:element ref="JobStatus" minOccurs="0"/>
				<xsd:element ref="JobLevel" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="JobCategory" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="validFrom" type="AnyDateTimeType"/>
			<xsd:attribute name="validTo" type="AnyDateTimeType"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="JobStatus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Code" type="xsd:string" minOccurs="0"/>
				<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="JobDescription" type="xsd:string"/>
	<xsd:element name="JobTitle" type="xsd:string"/>
	<xsd:element name="JobCategory">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Code" type="xsd:string" minOccurs="0"/>
				<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="JobLevel">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Code" type="xsd:string" minOccurs="0"/>
				<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
				<xsd:element ref="JobLevel" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="JobIdentifierType">
		<xsd:sequence>
			<xsd:element name="Id" type="xsd:string"/>
			<xsd:element name="Domain" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="IdIssuer" type="xsd:string" minOccurs="0"/>
						<xsd:element name="IdType" type="xsd:string" minOccurs="0"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== raml-apis/Jobvite/schemas/CPO/JobHeaderExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobHeader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ns.hr-xml.org/2007-04-15" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15 JobHeader.xsd" validFrom="2001-12-15" validTo="2002-02-15">
	<JobId>
		<Id>Programmer</Id>
		<Domain>
			<IdIssuer>ABC Company</IdIssuer>
			<IdType>Id</IdType>
		</Domain>
	</JobId>
	<JobTitle>Associate Programmer</JobTitle>
	<JobDescription>Program according to design documents. Conduct unit testing on all work. Document changes made to programs.</JobDescription>
	<JobStatus>
		<Code>1</Code>
		<Description>Active</Description>
	</JobStatus>
	<JobLevel type="Family">
		<Code>Salaried</Code>
		<Description>Salaried, Non-executive Job Family</Description>
		<JobLevel type="Type">
			<Code>PROG</Code>
			<Description>Programmer</Description>
			<JobLevel type="Step">
				<Code>1</Code>
				<Description>Programmer 1</Description>
			</JobLevel>
		</JobLevel>
	</JobLevel>
	<JobCategory type="HighTech">
		<Code>Technical</Code>
		<Description>High Tech Employee</Description>
	</JobCategory>
</JobHeader>
