=== raml-apis/Jobvite/schemas/CPO/MilitaryHistory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ns.hr-xml.org/2007-04-15" xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: MilitaryHistory.xsd
Status: Recommendation
Date this version: 2007-04-15
Purpose: Defines the MilitaryHistory Schema
Author(s):  
Documentation: MilitaryHistory.html

Terms of license can be found in license.txt.

</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="./CPO/DateTimeDataTypes.xsd"/>
	<xsd:include schemaLocation="./CPO/ISOUtilities.xsd"/>
	<xsd:include schemaLocation="./CPO/IdentifierTypes.xsd"/>
	<xsd:include schemaLocation="./CPO/UserArea.xsd"/>
	<xsd:include schemaLocation="./CPO/FlexibleDates.xsd"/>
	<xsd:element name="MilitaryHistory" type="MilitaryHistoryType"/>
	<xsd:complexType name="MilitaryHistoryType">
		<xsd:sequence>
			<xsd:element name="CountryServed" type="CountryCodeType"/>
			<xsd:element name="ServiceNumber" type="EntityIdType" minOccurs="0"/>
			<xsd:element name="ServiceDetail" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="UnitOrDivision" type="xsd:string" minOccurs="0"/>
						<xsd:element name="RankAchieved" type="RankAchievedType" minOccurs="0"/>
						<xsd:element name="DatesOfService" type="DatesOfServiceType"/>
						<xsd:element name="Campaign" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="AreaOfExpertise" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="RecognitionAchieved" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="DisciplinaryAction" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element name="DischargeStatus" type="xsd:string" minOccurs="0"/>
						<xsd:element ref="UserArea" minOccurs="0"/>
					</xsd:sequence>
					<xsd:attribute name="branch" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ServiceStatus" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Comments" type="xsd:string" minOccurs="0"/>
			<xsd:element ref="UserArea" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="RankAchievedType">
		<xsd:sequence>
			<xsd:element name="StartRank" type="xsd:string" minOccurs="0"/>
			<xsd:element name="CurrentOrEndRank" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="DatesOfServiceType">
		<xsd:sequence>
			<xsd:element name="StartDate" type="FlexibleDatesType"/>
			<xsd:element name="EndDate" type="FlexibleDatesType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== raml-apis/Jobvite/schemas/CPO/MilitaryExample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MilitaryHistory xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
MilitaryHistory.xsd">
	<CountryServed>US</CountryServed>	
	<ServiceNumber>
		<IdValue>977246</IdValue>
	</ServiceNumber>
	<ServiceDetail branch="Army">
		<UnitOrDivision>Fort SIll, OK</UnitOrDivision>
		<RankAchieved>
			<CurrentOrEndRank>Captain</CurrentOrEndRank>
		</RankAchieved>
		<DatesOfService>
			<StartDate>
				<AnyDate>1991-02-01</AnyDate>
			</StartDate><EndDate>
				<AnyDate>1998-06-01</AnyDate>
			</EndDate>
		</DatesOfService>
		<Campaign>Gulf War</Campaign>
		<AreaOfExpertise>Successfully led field logistics and maintenance operation centers and developed operational and combat standard operation procedures (SOP). Developed and implemented a battalion recovery operation procedure, which saved critical training time and funds. Led maintenance teams to win Corps level awards in maintenance excellence four different times. As both a battery operations officer and battalion maintenance officer I successfully led the tactical deployments of my respective units. </AreaOfExpertise>
		<RecognitionAchieved>Army Good Conduct Medal</RecognitionAchieved>
	</ServiceDetail>
</MilitaryHistory>
