=== raml-apis/Jobvite/schemas/CPO/PatentHistory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ns.hr-xml.org/2007-04-15" xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="2007-04-15">
	<xsd:annotation>
		<xsd:documentation>
"Copyright  The HR-XML Consortium. All Rights Reserved. http://www.hr-xml.org"
Name: PatentHistory.xsd
Status: Recommendation
Date this version: 2007-04-15
Purpose: Defines XSD for Information about Patents claimed on a resume, CV, etc.
Editor: Chuck Allen
Documentation: 

Terms of license can be found in license.txt.

		</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="./CPO/DateTimeDataTypes.xsd"/>
	<xsd:include schemaLocation="./CPO/EntityIdType.xsd"/>
	<xsd:include schemaLocation="./CPO/ISOUtilities.xsd"/>
	<xsd:include schemaLocation="./CPO/ContactMethod.xsd"/>
	<xsd:include schemaLocation="./CPO/xStringPatternExtensionType.xsd"/>
	<xsd:element name="PatentHistory" type="PatentHistoryType"/>
	<xsd:complexType name="PatentHistoryType">
		<xsd:sequence>
			<xsd:element name="Patent" type="PatentDescriptionType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PatentDescriptionType">
		<xsd:sequence>
			<xsd:element name="PatentTitle" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Inventors" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>A patent has one or more applicants. An applicant is the person or corporate body that applies for the patent and intends to 'work' the invention (to manufacture or license the technology).  Under US law the applicants must be the inventor(s) except in exceptional circumstances.  On a resume or CV listing patents held or submitted, an individual might use the "Applicants" component when the patent is held or was filed with others ("co-applicants").</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="InventorName" type="xsd:string" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="PatentDetail" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="IssuingAuthority" minOccurs="0">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:string">
										<xsd:attribute name="countryCode" type="CountryCodeType"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="PatentMilestone" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="Id" type="xsd:string" minOccurs="0"/>
									<xsd:element name="Status" type="PatentStatusTypes" minOccurs="0"/>
									<xsd:element name="Date" type="AnyDateTimeNkNaType" minOccurs="0"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="Link" type="InternetWebAddressType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="PatentStatusTypes">
		<xsd:union memberTypes="PatentStatusTypeTypes xStringPatternExtensionType"/>
	</xsd:simpleType>
	<xsd:simpleType name="PatentStatusTypeTypes">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PatentIssued"/>
			<xsd:enumeration value="PatentPending"/>
			<xsd:enumeration value="PatentFiled"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== raml-apis/Jobvite/schemas/CPO/PatentHistoryExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<PatentHistory xmlns="http://ns.hr-xml.org/2007-04-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ns.hr-xml.org/2007-04-15
PatentHistory.xsd">
	<Patent>
		<PatentTitle>Optical Fiber Image Conduit and Method Using Same</PatentTitle>
		<Description>The Ultrascope is a camera accessory that attaches to existing photographic and video cameras to access small viewing areas that are normally restricted to more expensive equipment. The present invention employs a steering system to view hard-to-reach regions. The materials that are used for the invention make the product an attractive and affordable accessory. The design makes the product simple to use, available to the professional and novice user. Additionally, it improves visibility in small, dark areas and is made from durable materials.</Description>
		<Inventors>
			<InventorName>Jorge O. Sanchez</InventorName>
		</Inventors>
		<PatentDetail>
			<IssuingAuthority countryCode="US">US Patent and Trademark Office</IssuingAuthority>
			<PatentMilestone>
				<Status>PatentFiled</Status>
				<Date>1996-06-01</Date>
			</PatentMilestone>
			<PatentMilestone>
				<Id>08-76853</Id>
				<Status>PatentPending</Status>
				<Date>1997-09-01</Date>
			</PatentMilestone>
			<PatentMilestone>
				<Id>5,960,145</Id>
				<Status>PatentIssued</Status>
				<Date>1999-09-01</Date>
			</PatentMilestone>
		</PatentDetail>
		<Link>http://patents.patentbase.com/ultrascope</Link>
	</Patent>
</PatentHistory>
