=== raml-apis/Jobvite/schemas/employee-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "CompanyId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ImporterEmail" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ReportEmail" : {
      "type" : "string" ,
      "required" : false
    } ,
    "DoNotSyncOnWarnings" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "OverwriteEmployeeNamesAndEmail" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "Employees" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "FirstName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LastName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "DepartmentName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LocationName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "RegionName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "SubsidiaryName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Role" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Title" : {
              "type" : "string" ,
              "required" : false
            } ,
            "EmployeeId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Address" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Address2" : {
              "type" : "string" ,
              "required" : false
            } ,
            "City" : {
              "type" : "string" ,
              "required" : false
            } ,
            "State" : {
              "type" : "string" ,
              "required" : false
            } ,
            "PostalCode" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Country" : {
              "type" : "string" ,
              "required" : false
            } ,
            "HomePhone" : {
              "type" : "string" ,
              "required" : false
            } ,
            "WorkPhone" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Mobile" : {
              "type" : "string" ,
              "required" : false
            } ,
            "CustomFields" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "Key" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "Value" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                }
              ]
            }
          }
        } , {
          "type" : "object" ,
          "properties" : {
            "FirstName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LastName" : {
              "type" : "string" ,
              "required" : false
            } ,
            "Name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LocationName" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/Jobvite/examples/employee-example.json
{"CompanyId":"qoV9Vfw7",
"ImporterEmail":"hr@oracle.xxx",
"ReportEmail":"hr@oracle.xxx",
"DoNotSyncOnWarnings":false,
"OverwriteEmployeeNamesAndEmail":false,
"Employees":[
{
"FirstName":"Mary995",
"LastName":"Doe",
"Name":"Mary995.Doe@JDInc.us",
"DepartmentName":"",
"LocationName":"Burlingame",
"RegionName":"",
"SubsidiaryName":"",
"Role":"Administrator",
"Title":"Architect",
"EmployeeId":"",
"Address":"Mehboob Nagar",
"Address2":"",
"City":"Latur",
"State":"MH",
"PostalCode":"413512",
"Country":"India",
"HomePhone":"023995252111",
"WorkPhone":"0999581995492",
"Mobile":"",
"CustomFields":[
{"Key":"VP",
"Value":"joe@JDInc.us"},
{"Key":"Reports To",
"Value":"Mose995.Doe@JDInc.us"}
]
},
{
"FirstName":"Mose995",
"LastName":"Doe",
"Name":"Mose995.Doe@JDInc.us",
"LocationName":"Burlingame"
},
{
"FirstName":"Mane995"
,"LastName":"Doe"
,"Name":"Mane995.Doe@JDInc.us"
,"LocationName":"Burlingame"
}
]
}
